# Configurações do Banco de Dados
db.url=jdbc:postgresql://localhost:3000/galeria_artes
db.user=postgres
db.password=postgres

# Configurações do JavaFX
javafx.stage.title=Galeria de Artes
javafx.stage.width=800
javafx.stage.height=600